"""Recover the Bank's ICR self-rating from the Projects API, with a repair.

WHAT WAS OBSERVED (2026-09-15, reproducible with `make disagreement`).

The Projects API `icr_ratings` block carries the Bank's own ICR self-ratings.
Two things about it are wrong out of the box, and both were established by
measurement rather than assumption:

1. The list can carry repeated elements, so src/fetch_projects.py deduplicates
   before reading any value. Observed across the 6,381 projects that have the
   block: 82.4% show no repetition at all (raw element count equals distinct
   count) and the rest repeat, up to 144 raw elements.

   WITHDRAWN CLAIM. An earlier version of this docstring said the block length
   "follows k*(k+1) (2, 6, 12, 20, 30, ...)". That is false, and the project's
   own data refutes it: observed raw counts include 1, 3, 4, 9, 25, 121 and 144,
   none of which has that form. No rule governing the block length is asserted
   here, because none was established, and the deduplication does not need one.

2. The value "Satisfactory" never appears. In its place the API emits
   "Substantial", a value from the four-point risk scale. Evidence, from the
   crosstab of the API field against the independently published GovTech
   workbook column "ICR Out" (src/govtech.py):

     API icr_outratingind == "Substantial"  ->  workbook "S" in 575 of 579
                                                rated rows (99.3%)
     API emits "Satisfactory"               ->  0 rows in the whole overlap
     diagonal elsewhere (matched/row total):
         HS 41/43, MS 534/541, MU 168/169, U 54/54, HU 7/7

   The same defect appears independently on `icr_borroverall`, the Bank's
   self-rating of borrower performance, against the workbook column "ICR BoP":
     "Substantial" -> workbook "S" in 380 of 381 rated rows (99.7%), and
     "Satisfactory" is emitted 0 times there as well.
     diagonal elsewhere: HS 26/27, MS 475/480, MU 136/136, U 39/40, HU 2/2

   These counts are regenerated by `make disagreement` and written to
   results/icr_repair_validation_crosstab.csv and
   results/icr_repair_validation_crosstab_borrower.csv.

   Two separate fields, two independent confirmations, and an otherwise clean
   diagonal. The repair below therefore maps "Substantial" to "Satisfactory"
   INSIDE the icr_ratings block only.

LIMIT OF THE CLAIM. We did not read World Bank source code or a field
dictionary describing this behaviour, so the CAUSE is unknown. What is
established is the mapping between the two published sources on the overlapping
rows. Every number derived from the repair is reported alongside the same
number computed on the GovTech-only subset, which needs no repair.
"""
from __future__ import annotations

import pandas as pd

from . import scales

# Fields in the icr_ratings block that are on the SIX-POINT outcome scale. The
# repair applies to these and only these.
ICR_BLOCK_FIELDS = ["icr_outratingind", "icr_overallrating", "icr_borroverall",
                    "icr_borrgovt", "icr_borrimplegency", "icr_bankqualityentry",
                    "icr_banksupervision"]

# Fields in the SAME block that are on a four-point RISK scale, where
# "Substantial" is a genuine value and the repair would corrupt it. These are
# excluded from repair_frame by construction, and repair_frame raises if a
# caller passes one.
ICR_RISK_FIELDS = ["icr_completion_riskdo"]


def repair_icr_value(value):
    """Map an icr_ratings value onto the six-point outcome scale.

    "Substantial" inside this block means "Satisfactory" (see module docstring).
    Applied ONLY to icr_ratings fields, never to IEG fields, and never to a
    genuine four-point field such as M&E quality or risk to development outcome.
    """
    c = scales.canonicalise(value)
    if c == "Substantial":
        return "Satisfactory"
    return c


def repaired_six_point(value):
    return scales.to_six_point(repair_icr_value(value))


def repair_frame(df: pd.DataFrame, fields=None) -> pd.DataFrame:
    fields = fields or ICR_BLOCK_FIELDS
    bad = sorted(set(fields) & set(ICR_RISK_FIELDS))
    if bad:
        raise ValueError(
            f"refusing to apply the outcome-scale repair to risk-scale "
            f"field(s) {bad}; 'Substantial' is a real value there")
    out = df.copy()
    for f in fields:
        if f in out.columns:
            out[f"{f}_repaired"] = out[f].map(repair_icr_value)
            out[f"{f}_six_point"] = out[f].map(repaired_six_point)
    return out


def disagreement_table(df: pd.DataFrame, bank_col: str, ieg_col: str,
                       year_col: str) -> pd.DataFrame:
    """Bank self-rating versus IEG rating, on the six-point scale, by year.

    `df` must already carry numeric six-point columns. Rows where either side is
    unrated are dropped and counted.
    """
    d = df[[bank_col, ieg_col, year_col]].dropna()
    if d.empty:
        return pd.DataFrame(columns=["year", "n", "agree", "bank_higher",
                                     "bank_lower", "mean_gap"])
    d = d.copy()
    d["agree"] = (d[bank_col] == d[ieg_col]).astype(float)
    d["bank_higher"] = (d[bank_col] > d[ieg_col]).astype(float)
    d["bank_lower"] = (d[bank_col] < d[ieg_col]).astype(float)
    d["gap"] = d[bank_col] - d[ieg_col]
    g = d.groupby(year_col).agg(
        n=("agree", "size"), agree=("agree", "mean"),
        bank_higher=("bank_higher", "mean"), bank_lower=("bank_lower", "mean"),
        mean_gap=("gap", "mean")).reset_index().rename(columns={year_col: "year"})
    g["year"] = g["year"].astype(int)
    return g
